# Generated by Django 2.2 on 2020-03-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(related_name='User_likes', to='wall_app.User'),
        ),
    ]
