# Generated by Django 2.2 on 2020-03-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0005_message_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='total_likes',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
