# Generated by Django 2.2 on 2020-03-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='wish_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wish',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
