# Generated by Django 2.2 on 2020-03-20 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20200320_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='wish_count',
        ),
    ]
