# Generated by Django 2.2 on 2020-03-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_app', '0003_auto_20200312_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='desc',
            field=models.TextField(default='prev show', null=True),
        ),
    ]
